### ISSUE TITLE
Separate UnifiedGroups.xml per tenant

### ISSUE THREAD

**Issue by cunninghamp** [cunninghamp/Office365GroupsReport#11]
Use same credential for EXO to connect to Msol and pull tenant details so that UnifiedGroups.xml can be stored per-tenant, useful for running against multiple tenants without copying script to separate folders for each one.

**Comment by chrisbrownie** [comment]
What about just using `(Get-OrganizationConfig).Name` or `(Get-OrganizationConfig).Guid` to uniquely identify the tenant? Connecting to Msol will add duration and will add a dependency we can possibly avoid.

**Comment by cunninghamp** [comment]
That'll work too.

**Comment by chrisbrownie** [comment]
Resolved in #14 

`UnifiedGroups.xml` is now `UnifiedGroups-contoso.onmicrosoft.com.xml`
