### ISSUE TITLE
Once a group has been discovered as "modified" and reported on, should it always be listed as modified? Or, should it be back in "Unmodified" going forward? It will be easier to see future changes if it is reclassified back as “Unmodified since last report” - Thanks

### ISSUE THREAD

**Issue by Roger-at-GT** [cunninghamp/Office365GroupsReport#16]

**Comment by Roger-at-GT** [comment]
Actually, this may be an issue with our environment, I have made some test changes and see them in the report as expected, but one particular group seems stuck in the modified section with no new  changes and repeated report runs.

**Comment by cunninghamp** [comment]
The expected behavior is that it will report as modified once, and then next time if it hasn't been modified since the last report it should appear as unmodified.

That comparison relies on successfully writing the latest groups data back to an XML file on the file system. It may be that step is failing. Can you check whether that file has been updated next time the script runs?

**Comment by Roger-at-GT** [comment]
It has been updating the XML file. Upon further testing it seems to be related to the group owner or specifically owners. The group that continuously shows up in the “Modified Groups found” section has 2 owners and when we remove one of them it behaves as expected and shows the change on the next report run and then shows as “Unmodified” on subsequent reports.

**Comment by cunninghamp** [comment]
So if the group has two (or presumably anything more than one) owners, it will repeatedly and incorrectly be listed as Modified?

**Comment by Roger-at-GT** [comment]
That is my experience so far, I will be able to test more later today.

**Comment by Roger-at-GT** [comment]
Yes, when I remove all but one owner, the group goes to unmodified when you run the report two times after the change.

**Comment by cunninghamp** [comment]
Thanks. We'll repro that and get a fix added.

**Comment by chrisbrownie** [comment]
Repro'd, working on a fix now.
![image](https://cloud.githubusercontent.com/assets/5036744/20026421/6cbc72bc-a34e-11e6-89e4-a3397f1a44f2.png)

**Comment by chrisbrownie** [comment]
Hi @Roger-at-GT, this has been fixed. Groups will now report correctly when their manager attribute is either an array of multiple managers or is changed.

If you want to test the update, please try running the script from the development branch.
